# this look a bit random right now, but it will be used to generate the parameters for the model
feature_selection:
  feature_selection: "rfe"
  baseline_model_params:
    n_estimators: 100
    max_depth: 5
    random_state: 42
